### PR TITLE
Feature/tv ui

### PR DESCRIPTION
**Pull request by ninovanhooff**
Adds some eye candy for the TV UI

Also drags the Settings icon closer to the center of attention, and add some visual feedback of what icon is currently selected and focused.

Note: Built on top of my previous PR https://github.com/abrenoch/hyperion-android-grabber/pull/32 , merging that one first will give a clear overview of the changes

### CODE REVIEW

**Comment by abrenoch** [comment]
One more thing I noticed: If you toggle the grabber on & off a few times rapidly, the toast message will stick around for a hilariously long time (I think 20 second x the number of toggles). Is there maybe a way to prevent creating a new toast if one is already displayed & dismiss it when the app loses focus?

**Comment by ninovanhooff** [comment]
Thanks for the feedback! The ui elements thing is super weird. I'll look into both issues. A simple solution for the toast might be to not make it a toast at all and just have a text view at the bottom screen that is always showing when the grabber is turned on. Might be less 'nagging' to ppl who have used the app for a few times already

**Comment by ninovanhooff** [comment]
Could not reproduce the assets issue. Im also using a shield (2015 16GB). 

I tried a debug build because I don't have the signing key for a release build.
Android Studio: build variants panel in the lower left.

What might help:

- Make sure you are up to date with the git branch and don't have any changes
- Build > clean project, Build> Rebuild project
- press the debug button

The icons show for me, both when turned on and turned off

Do the buttons work for you, event hough you can't see them?

**Comment by ninovanhooff** [comment]
@abrenoch, could you try the above for me?

**Comment by abrenoch** [comment]
Will give this a try when I get home tonight!

**Comment by abrenoch** [comment]
Okay got a little more time to fiddle with it! The steps above didn't help unfortunately, but I think I did find what was going on.

When I was in the layout view it was showing a problem loading the constraintlayout element, so I just clicked the 'fix' button provided and the layout previewed correctly and it ran correctly on the shield.

I tried to reproduce what happened (so I could actually figure out what that fix button was doing), but when I loaded up the code from your branch everything worked fine this time... So I probably messed up something when switching between the projects!

Anyway, I dig it! We can merge the PR now, or if you wanted to fiddle with the notification at all could wait for that. Your call!

**Comment by ninovanhooff** [comment]
Go ahead and merge it, I'll do the notification after the scanner is
finished.

**Pull request merged**
