### PR TITLE
Reconnect if connection lost

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
Sorry, my english is not very good but creating pull request is easy. :-)
This PR does not solve the problem in Issue #25, but may be helpful for the comment below.

regards Paulchen

### CODE REVIEW

**Comment by abrenoch** [comment]
Hey this looks great, thanks for contributing!

Excited to try out the changes! :grin:

**Comment by Paulchen-Panther** [comment]
If there is anything else I can do, let me know.

**Comment by Paulchen-Panther** [comment]
Ops i see there is an infinity loop in the thread. i will fix this asap.

**Comment by abrenoch** [comment]
Was that loop the `while` block inside `HyperionThread.run`? When I glossed over the changes quick that was the only area that stood out to me!

**Comment by Paulchen-Panther** [comment]
All fixed.
Yes it was the while block in HyperionThread.run(). The finally block has never leaves the loop.

**Comment by abrenoch** [comment]
Everything looks good on my end! Thanks a lot for contributing!

Also big thanks for the buildscript fix - I just updated android studio today and it definitely saved me the trouble of figuring out what changed!

**Comment by abrenoch** [comment]
Hey @Paulchen-Panther, if you have the time would you mind adding these changes to the mobile version as well? If not thats fine, I can take care of it when I have more time!

I should take some time to learn how to use sub-modules in git to keep the code between the tv & mobile build synced better!

**Comment by Paulchen-Panther** [comment]
Yes I do

**Pull request merged**
