### PR TITLE
TV toggle automation

### PR DESCRIPTION
**Pull request by ninovanhooff**
Adds a Toggle Activity, which is exposed to automation tools and custom launchers on the TV build. Intended for use with the Button Mapper app

### CODE REVIEW

**Comment by ninovanhooff** [comment]
Note that this PR adds a string resource. please make sure it exists in Lokalise

**Comment by abrenoch** [comment]
Hey @ninovanhooff I see you mentioned this PR adds a string resource, but I'm not seeing it in the changed files anywhere? I see the key name is `toggle_activity_label`, but not seeing the value anywhere.

Should I just add it to lokalise then sync in that translation?

**Comment by ninovanhooff** [comment]
> Should I just add it to lokalise then sync in the change?

Could catch. Got lost somewhere, added it to the tv-specific strings
Also hidden the toggle activity from recents, like the boot activity.

**Comment by abrenoch** [comment]
That new string is available in lokalise too, just FYI!

**Pull request merged**
