### PR TITLE
Encoder fixes

### PR DESCRIPTION
**Pull request by abrenoch**
A couple (thankfully simple) fixes related to the screen encoders. May also fix issue #23

### CODE REVIEW

**Comment by abrenoch** [comment]
Anyone mind trying out the changes from e0c82c99e309e224607c419aaf944a0dee31b324 for me? Only added a few lines but it seems like it is doing the trick. I left the grabber running on my phone overnight (with the screen off), and it was still running and sending data when I woke it up this morning, so I think this may fix the wake issue with the non-ogl grabber!

**Comment by NisseDILLIGAF** [comment]
This is working for me on my Shield Android TV...
I only tried and suspend it for a couple of minutes, and my PiZero with hyperion shuts down during this time (usb power connected on TV)
When I wake it again and the Pi has started up, it connects! very nice 👍 
I get this error in Logcat, but maybe it doesn't matter...

```
06-01 22:49:08.568 18120-18149/com.abrenoch.hyperiongrabber.tv E/ERROR: COULD NOT CONNECT TO HYPERION INSTANCE
06-01 22:49:08.569 18120-18149/com.abrenoch.hyperiongrabber.tv E/ERROR: Connection reset
06-01 22:49:08.569 18120-18149/com.abrenoch.hyperiongrabber.tv E/DEBUG: AUTOMATIC RECONNECT ENABLED. CONNECTING ...
06-01 22:49:08.569 18120-18149/com.abrenoch.hyperiongrabber.tv W/System.err: java.net.SocketException: Connection reset
06-01 22:49:08.570 18120-18149/com.abrenoch.hyperiongrabber.tv W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:192)
        at java.net.SocketInputStream.read(SocketInputStream.java:120)
        at com.abrenoch.hyperiongrabber.common.network.Hyperion.receiveReply(Hyperion.java:136)
        at com.abrenoch.hyperiongrabber.common.network.Hyperion.sendRequest(Hyperion.java:126)
06-01 22:49:08.571 18120-18149/com.abrenoch.hyperiongrabber.tv W/System.err:     at com.abrenoch.hyperiongrabber.common.network.HyperionThread$1.sendFrame(HyperionThread.java:25)
        at com.abrenoch.hyperiongrabber.common.HyperionScreenEncoder$3.onImageAvailable(HyperionScreenEncoder.java:115)
        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:658)
06-01 22:49:08.572 18120-18149/com.abrenoch.hyperiongrabber.tv W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by abrenoch** [comment]
Hey @NisseDILLIGAF glad it is working for you! Would you mind trying out the most recent commit and letting me know if it still works fine please? I had found a few instances where it would fail to resume grabbing, so hopefully the most recent commit will fix that!

Also, the error in the log is no surprise there (it appears to happen when the socket is disconnected) but maybe it could be handled better.

Thanks for trying out the changes!

**Comment by NisseDILLIGAF** [comment]
The most recent commit works for me... It connects after suspend.
But it didn't work over night..  but that didn't work earlier either... Maybe a doze thing?
I tried to leave Logcat (over wifi) on last night, but it had disconnected this morning.
Will try to deactivate doze for android-grabber, and see what happens tomorrow morning.

Do anyone have a good way to Logcat a app on android TV without being connected?

logcat
```
06-09 09:51:36.133 8662-8662/com.abrenoch.hyperiongrabber.tv D/DEBUG: HyperionScreenEncoder.displayCallback.onPaused triggered
06-09 12:47:44.885 8662-8662/com.abrenoch.hyperiongrabber.tv D/DEBUG: HyperionScreenEncoder.displayCallback.onResumed triggered
06-09 12:48:11.925 8662-8693/com.abrenoch.hyperiongrabber.tv E/ERROR: COULD NOT CONNECT TO HYPERION INSTANCE
    Connection reset
06-09 12:48:11.925 8662-8693/com.abrenoch.hyperiongrabber.tv E/DEBUG: AUTOMATIC RECONNECT ENABLED. CONNECTING ...
```

**Comment by abrenoch** [comment]
@NisseDILLIGAF thanks for trying that again! For testing the wake behavior seems to be pretty consistent now... I have had mixed success leaving it running for long periods of time too. Both my phone & the shield  reconnected for me after a night of being off (shield even worked after a couple days), but it doesn't seem to be 100% yet for long-term sleeps.

I have a hunch what it might be (something with the max imageReader images and/or the usage of acquireLatestImage vs acquireNextImage), but it might be out of the scope of the wake behavior. Or at least that will be my excuse to get this PR merged 😆 

I'm not certain about the logging question actually, that is why I have been testing a lot of this wake behavior on my phone rather than the shield. I'm sure there is a good way I'm just not aware of it!

**Pull request merged**
